-- Create public profiles table linked to Supabase Auth
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  name text,
  email text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- Reporters Table
create table public.reporters (
  id bigint generated by default as identity primary key,
  name text not null,
  designation text,
  photo text
);

-- News Table
create table public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  content text not null,
  category_id bigint references public.categories on delete set null,
  featured_image text,
  author_id bigint references public.reporters on delete set null,
  views integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Videos Table
create table public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  youtube_url text not null,
  thumbnail text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Advertisements Table
create table public.advertisements (
  id bigint generated by default as identity primary key,
  banner_image text not null,
  start_date date,
  end_date date
);

-- Comments Table
create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  news_id bigint references public.news on delete cascade not null,
  comment text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Reactions Table
create table public.reactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  news_id bigint references public.news on delete cascade not null,
  reaction_type text not null,
  unique(user_id, news_id) -- A user can react only once per news article (or we can handle it differently)
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.reporters enable row level security;
alter table public.news enable row level security;
alter table public.videos enable row level security;
alter table public.advertisements enable row level security;
alter table public.comments enable row level security;
alter table public.reactions enable row level security;

-- Basic Policies (Adjust as needed for full production)

-- Profiles: Anyone can read profiles, users can update their own
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- Categories, Reporters, News, Videos, Ads: Viewable by everyone, editable by admins
-- Note: 'admin' role logic would need a more robust check in a real app, here we just allow read for everyone
create policy "Categories are viewable by everyone." on public.categories for select using (true);
create policy "Reporters are viewable by everyone." on public.reporters for select using (true);
create policy "News are viewable by everyone." on public.news for select using (true);
create policy "Videos are viewable by everyone." on public.videos for select using (true);
create policy "Ads are viewable by everyone." on public.advertisements for select using (true);

-- Comments & Reactions: Viewable by everyone, insertable by authenticated users
create policy "Comments are viewable by everyone." on public.comments for select using (true);
create policy "Authenticated users can insert comments." on public.comments for insert with check (auth.uid() = user_id);
create policy "Users can update their own comments." on public.comments for update using (auth.uid() = user_id);
create policy "Users can delete their own comments." on public.comments for delete using (auth.uid() = user_id);

create policy "Reactions are viewable by everyone." on public.reactions for select using (true);
create policy "Authenticated users can insert reactions." on public.reactions for insert with check (auth.uid() = user_id);
create policy "Users can update their own reactions." on public.reactions for update using (auth.uid() = user_id);
create policy "Users can delete their own reactions." on public.reactions for delete using (auth.uid() = user_id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
